# Generated by Django 4.0.5 on 2022-06-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_questionmodel_author_alter_responsemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculum/'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='live_classes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='announcement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='assigments',
            field=models.FileField(blank=True, null=True, upload_to='assigments/'),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='content/'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='assigmetns',
            field=models.FileField(blank=True, null=True, upload_to='assigments/student/'),
        ),
    ]
