# Generated by Django 4.0.5 on 2022-06-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coursemodel_curriculum_coursemodel_live_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='completed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='completed',
            field=models.FloatField(default=0),
        ),
    ]
